const productos = [
    {
        "id": 1,
        "producto": "Bowl",
        "img": "",
        "precio": 4620,
        "color": "Azul",
        "categoria": "Cocina",
        "oferta": true,
    },
    {
        "id": 2,
        "producto": "Cuchara",
        "img": "",
        "precio": 2200,
        "color": "Dorado",
        "categoria": "Cocina",
        "oferta": false,
    },
    {
        "id": 3,
        "producto": "Frasco",
        "img": "",
        "precio": 8690,
        "color": "Naranja",
        "categoria": "Cocina",
        "oferta": false,
    },
    {
        "id": 4,
        "producto": "Pinches",
        "img": "",
        "precio": 1750,
        "color": "Plateado",
        "categoria": "Cocina",
        "oferta": false,
    },
    {
        "id": 5,
        "producto": "Taza",
        "img": "",
        "precio": 3490,
        "color": "Gris",
        "categoria": "Cocina",
        "oferta": false,
    },
    {
        "id": 6,
        "producto": "Almohadon1",
        "img": "",
        "precio": 11100,
        "color": "Crudo",
        "categoria": "Dormitorio",
        "oferta": true,
    },
    {
        "id": 7,
        "producto": "Almohadon2",
        "img": "",
        "precio": 6900,
        "color": "Verde",
        "categoria": "Dormitorio",
        "oferta": false,
    },
    {
        "id": 8,
        "producto": "Manta1",
        "img": "",
        "precio": 69300,
        "color": "Mostaza",
        "categoria": "Dormitorio",
        "oferta": false,
    },
    {
        "id": 9,
        "producto": "Manta2",
        "img": "",
        "precio": 28000,
        "color": "Gris",
        "categoria": "Dormitorio",
        "oferta": false,
    },
    {
        "id": 10,
        "producto": "Almohadon3",
        "img": "",
        "precio": 10200,
        "color": "Negro",
        "categoria": "Dormitorio",
        "oferta": false,
    },
    {
        "id": 11,
        "producto": "Portavela",
        "img": "",
        "precio": 2530,
        "color": "Dorado",
        "categoria": "Deco",
        "oferta": true
    },
    {
        "id": 12,
        "producto": "Alfombra",
        "img": "",
        "precio": 8900,
        "color": "Negra",
        "categoria": "Deco",
        "oferta": false,
    },
    {
        "id": 13,
        "producto": "Fanal",
        "img": "",
        "precio": 25300,
        "color": "Dorado",
        "categoria": "Deco",
        "oferta": false,
    },
    {
        "id": 14,
        "producto": "Perchero",
        "img": "",
        "precio": 2100,
        "color": "Plateado",
        "categoria": "Deco",
        "oferta": false,
    },
    {
        "id": 15,
        "producto": "Tirador",
        "img": "",
        "precio": 3600,
        "color": "Dorado",
        "categoria": "Deco",
        "oferta": false,
    },
]